artifacts_dir : "artifacts"

dataingestion_config :
  root_dir : "artifacts/data_ingestion"
  source_url: "" #mention the url from where you want to download the dataset
  download_path : "artifacts/data_ingestion/data.zip"
  unzip_path : "artifacts/data_ingestion"
